
services:

  db:
    image: postgres:13-alpine
    restart: unless-stopped
    command: ["-c", "datestyle=iso,dmy"]
    environment:
      POSTGRES_DB: MaarchCourrier
      POSTGRES_USER: maarch
      POSTGRES_PASSWORD: maarch
      POSTGRES_HOST_AUTH_METHOD: "trust"

  app:
    image: local/courrier:main
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "healthcheck.sh" ]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 5s
    volumes:
      - ${DOCSERVERS_ROOT_PATH}:/opt/maarch/docservers:rw
      - ${CUSTOM_PATH}:/var/www/html/MaarchCourrier/custom:rw
      - ${LIBRAIRIES_PATH}:/app/librairies
      - ${CRON_CONFIGURATION_PATH}:/etc/cron.d
    ports:
      - ${APP_PORT}:80
    environment:
      LIBRARIES_DIR: /app/librairies
      MAARCH_TMP_DIR: ${MAARCH_TMP_DIR}

